// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BTFft
NumericVector BTFft(int m, int n, List interval, NumericVector z, NumericVector psi);
RcppExport SEXP _aisoph_BTFft(SEXP mSEXP, SEXP nSEXP, SEXP intervalSEXP, SEXP zSEXP, SEXP psiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< List >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psi(psiSEXP);
    rcpp_result_gen = Rcpp::wrap(BTFft(m, n, interval, z, psi));
    return rcpp_result_gen;
END_RCPP
}
// Y2ft
List Y2ft(int m, int n, List interval, NumericVector z, NumericMatrix Y, NumericMatrix dN);
RcppExport SEXP _aisoph_Y2ft(SEXP mSEXP, SEXP nSEXP, SEXP intervalSEXP, SEXP zSEXP, SEXP YSEXP, SEXP dNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< List >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dN(dNSEXP);
    rcpp_result_gen = Rcpp::wrap(Y2ft(m, n, interval, z, Y, dN));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aisoph_BTFft", (DL_FUNC) &_aisoph_BTFft, 5},
    {"_aisoph_Y2ft", (DL_FUNC) &_aisoph_Y2ft, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_aisoph(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
