# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BTFft <- function(m, n, interval, z, psi) {
    .Call('_aisoph_BTFft', PACKAGE = 'aisoph', m, n, interval, z, psi)
}

Y2ft <- function(m, n, interval, z, Y, dN) {
    .Call('_aisoph_Y2ft', PACKAGE = 'aisoph', m, n, interval, z, Y, dN)
}

